name: sagemaker_env
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip=20.3.3
  - flask
  - nginx
  - zip
  - wget
  - curl
  - pip:
    - Flask-Testing
    - setuptools==39.1.0
    - annoy==1.8.3
    - Pillow==4.3.0
    - matplotlib==2.0.2
    - numpy==1.14.5
    - pandas==0.22.0
    - pygame==1.9.3
    - PyOpenGL==3.1.0
    - scipy==1.2.1
    - scikit-image==0.15.0
    - futures==3.1.1
    - boto3==1.9.23
    - minio==4.0.5
    - cryptography==3.2.1
    - kubernetes==7.0.0
    - opencv-python==4.1.1.26
    - bokeh==1.4.0
    - rl-coach-slim==1.0.0
    - retrying==1.3.3
    - eventlet==0.26.1
    - flask==1.1.2
    - gevent==20.6.2
    - gunicorn==20.0.4
    - h5py==2.10.0
    - pytest==5.4.1
    - pytest-cov==2.8.1
    - tensorflow==1.11
